CREATE OR REPLACE PROCEDURE CDM.logo wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
7
1e4 1ca
7dn/birZOoUEZBMH3em91c0x7jIwg3nMr9xqfHRDaGR8vnTLbVifqx7FLWHgt/LqjSvdvQJj
9TXeZQ1Ye7xInWCDZqChztP4MXI/Srf1hgc1QUDKMib7HEGvNwHOU0qo/4wRudjCRhvez4J7
8EhyZsFlwGTW8E/tbKiKWWyo+pyzg1tlYM9YkuM1b90exRIYcOa7ygpYJ0bzo3/0BNQ2hf91
cwDgBWGgkAlMnHVjMIojLnubZNrfF1mXsklBhjMd0I3D1wZP37cxft9LvfWVRIZBHTxx719W
NHGBlgdGjQJtHX1TV45FLOyqEv9ntCjbGR9cvVnsRKilW588dwWZlAVA+h2wD1sBtHU+SIw7
cKARS65wUmgegw5V+uaEf5/jc3VRf+Ynjo2UyccG3YgX8gu/sP68qGKVSfvScaAl2Is12D1I
xIGSHTUEW04KLKJc8Rg=
/
