CREATE OR REPLACE PROCEDURE CDM.banner wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
7
15e ef
oSv4bXfZIbD7Ahy/nVORUT4dOFMwg5nnm7+fMr2ywFxa8kfZDGIJabh0K48JuMAy/tJepZmB
CC2Lmyi/XyiyCNKzToHSMvD+uDL1UrIlaZahOxazchb618yxoCul571Qmeeb62maKF1Sr0Jx
205pU55IPwgcqLwiCP/5P6+oSj+oq0DsnlcqC+Xf5l55t/fsdeCAZ7d/RRsQekXhdlVMfzv7
B1uiB6wKT20qHaYMdOrq
/
