CREATE OR REPLACE FUNCTION CDM.fn_html_quote wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
18e 164
yiBFdzrF7MZ70dAFCVajyKDXZIIwg41pr9xqfHRDbmRLn95tcJS3n/z7wkfZxWP6iejrL+bz
qzUKdzJLQAUiQYn0r49GlmFPc4qweAoUgr7xpSWD8JrfM80QwaT7pvDoJdOnwwOtPe/m2Ryy
O2LwYcde5862D9kv0NSGFO+2Xb6K3myekTkictE2AectYEoKAmIKoVNbf+Jf6EdWJk0VyMvM
qxCqRMxFu0X17UInurEaDb8FBxPG0jEyHhBz/B5M/Ww43i8oliC3ry1K05s7fbip5+Koewfc
ZvmBPbG8UiSqXSVND0HSpVkKZhRrU0PyUje/AvqwjjfJXWgxtmLvFrAxlVt+jQHj
/
