CREATE OR REPLACE PROCEDURE CDM.data wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
7
339 1d6
ZeI2RlWaXe3Il9nazLLeEcuAVvkwg43xs0isfI5Av1WwfUxM4LSmv9bq3BPerH11kR/UdeGQ
7wp3UAaLdHKLCjtTl3azohLH/5pBu5lspPiM0blEIkB/9zYV/5k2pfMksnp9ROIFOYyx/3p1
dHELVwQGQiy/I7QgyqGdXVWYcWX1BUBz+rQE+IcdzcPhXOGcsETBmWDwMmbAFfEgZrZBq3Kt
199ADiWw4JVeNf1wmcpG5tNYmVuo+TdpA2j3FJF3PphzqaPzFxWzc8Oxm1f0lLFDR8MU76gB
xeUrSCvDMubJoUVnTRFBZ9jv22IKOlvoOmUaMYhQ4tY8AnAKy4NJZ9fXy6xfqkE0Ql1ZxPZE
00Mw+DvpXs111HMiE8HAjcm1IpuPmQ2Wd06nizuX/riNliW8WnIFgxfq+R7PLTOVI7xcmE9c
coC8ap1i9vuegZHZF5ktsfaa5Kbhgesu
/
