/*
ATTENZIONE
Se borra a copón los que no tienen capitulo
delete from EXCL_MAE_PRESU_04_EPIGRAFES
where ID in
(
select SUBID_EPIGRAFE
from MSTR_MAE_PRESU_04_EPIGRAFES
where SUBID_CONCEPTO
not in (select SUBID_CONCEPTO from MSTR_MAE_PRESU_03_CONCEPTOS)
)
*/

DROP MATERIALIZED VIEW MSTR_MAE_PRESU_04_EPIGRAFES;
DROP TABLE MSTR_MAE_PRESU_04_EPIGRAFES;

CREATE TABLE MSTR_MAE_PRESU_04_EPIGRAFES
(
   SUBID_EPIGRAFE   PRIMARY KEY
  ,DESCR_EPIGRAFE   NOT NULL
  ,SUBID_CAPITULO   NOT NULL /*REFERENCES MSTR_MAE_PRESU_01_CAPITULOS (SUBID_CAPITULO)*/
  ,SUBID_ARTICULO   NOT NULL /*REFERENCES MSTR_MAE_PRESU_02_ARTICULOS (SUBID_ARTICULO)*/
  ,SUBID_CONCEPTO   NOT NULL /*REFERENCES MSTR_MAE_PRESU_03_CONCEPTOS (SUBID_CONCEPTO)*/
--   La relación con el COAN no es 1 a 1 se crea una tabla auxiliaria para la referencia
--  ,NATID_SUBCONCEPTO_COAN --UNIQUE /*en las tablas del COAN el epigrafe viene con un digito menos*/
)
ORGANIZATION INDEX
PARALLEL 6
NOLOGGING
NOMONITORING
AS
   SELECT TO_NUMBER (ID) SUBID_EPIGRAFE, "DENOMINACIÓN PRINCIPAL" DESCR_EPIGRAFE
         ,TRUNC (TO_NUMBER (ID) / 10000) SUBID_CAPITULO, TRUNC (TO_NUMBER (ID) / 1000) SUBID_ARTICULO
         ,TRUNC (TO_NUMBER (ID) / 100) SUBID_CONCEPTO--, NATID_SUBCONCEPTO_COAN
     FROM EXCL_MAE_PRESU_04_EPIGRAFES --LEFT JOIN EXCL_MAE_REF_EPIGRAFES_COAN ON (SUBID_EPIGRAFE = TO_NUMBER (ID))
    WHERE NULL IS NOT NULL
   UNION ALL
   SELECT -1, 'Artículo presup. Erróneo', -1, -1, -1--, '-1'
     FROM DUAL
    WHERE NULL IS NOT NULL
   ORDER BY 1;

CREATE MATERIALIZED VIEW MSTR_MAE_PRESU_04_EPIGRAFES ON PREBUILT TABLE
AS
SELECT TO_NUMBER (ID) SUBID_EPIGRAFE, "DENOMINACIÓN PRINCIPAL" DESCR_EPIGRAFE
      ,TRUNC (TO_NUMBER (ID) / 10000) SUBID_CAPITULO, TRUNC (TO_NUMBER (ID) / 1000) SUBID_ARTICULO
      ,TRUNC (TO_NUMBER (ID) / 100) SUBID_CONCEPTO--, NATID_SUBCONCEPTO_COAN
  FROM EXCL_MAE_PRESU_04_EPIGRAFES --LEFT JOIN EXCL_MAE_REF_EPIGRAFES_COAN ON (SUBID_EPIGRAFE = TO_NUMBER (ID))
UNION ALL
SELECT -1, 'Artículo presup. Erróneo', -1, -1, -1--, '-1' 
FROM DUAL
ORDER BY 1;

  ALTER TABLE MSTR_MAE_PRESU_04_EPIGRAFES ADD
CONSTRAINT FK_MAE_PRESU_04_EPIGR_CAPIT
 FOREIGN KEY (SUBID_CAPITULO)
 REFERENCES MSTR_MAE_PRESU_01_CAPITULOS (SUBID_CAPITULO)
 ENABLE
 VALIDATE;
   ALTER TABLE MSTR_MAE_PRESU_04_EPIGRAFES ADD
CONSTRAINT FK_MAE_PRESU_04_EPIGR_ARTIC
 FOREIGN KEY (SUBID_ARTICULO)
 REFERENCES MSTR_MAE_PRESU_02_ARTICULOS (SUBID_ARTICULO)
 ENABLE
 VALIDATE;
  ALTER TABLE MSTR_MAE_PRESU_04_EPIGRAFES ADD
CONSTRAINT FK_MAE_PRESU_04_EPIGR_CONCE
 FOREIGN KEY (SUBID_CONCEPTO)
 REFERENCES MSTR_MAE_PRESU_03_CONCEPTOS (SUBID_CONCEPTO)
 ENABLE
 VALIDATE;

CREATE INDEX IDX_01_MSTR_MAE_PRESU_04
   ON MSTR_MAE_PRESU_04_EPIGRAFES (SUBID_CAPITULO)
   PARALLEL 6
   NOLOGGING
   COMPRESS;


CREATE INDEX IDX_02_MSTR_MAE_PRESU_04
   ON MSTR_MAE_PRESU_04_EPIGRAFES (SUBID_ARTICULO)
   PARALLEL 6
   NOLOGGING
   COMPRESS;


CREATE INDEX IDX_03_MSTR_MAE_PRESU_04
   ON MSTR_MAE_PRESU_04_EPIGRAFES (SUBID_CONCEPTO)
   PARALLEL 6
   NOLOGGING
   COMPRESS;

BEGIN
   DBMS_MVIEW.REFRESH ('MSTR_MAE_PRESU_04_EPIGRAFES');
END;
/

ALTER TABLE MSTR_MAE_PRESU_04_EPIGRAFES READ ONLY;
COMMIT;
GRANT SELECT ON MSTR_MAE_PRESU_04_EPIGRAFES TO COAN;
GRANT REFERENCES ON MSTR_MAE_PRESU_04_EPIGRAFES TO COAN;

EXEC dbms_stats.gather_table_stats( user, 'MSTR_MAE_PRESU_04_EPIGRAFES' );